# Generated by Django 5.1.7 on 2025-04-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0003_rename_entry_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('angry', 'Angry'), ('excited', 'Excited')], default='neutral', max_length=10),
        ),
    ]
