# Generated by Django 5.1.7 on 2025-04-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0004_diaryentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('excited', 'Excited')], default='neutral', max_length=10),
        ),
    ]
