# Generated by Django 5.1.7 on 2025-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0005_alter_diaryentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
