# Generated by Django 5.1.7 on 2025-04-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0007_alter_diaryentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('angry', 'Angry'), ('excited', 'Excited')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
