# Generated by Django 5.1.7 on 2025-04-25 19:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0010_alter_diaryentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
